"""Caracterización de `tiff.leer_cabecera` (F11.8, etapa 3), antes de partir `_leer_cabecera_de`.

`_leer_cabecera_de` mide ~170 líneas y mezcla tres cosas: reconocer la marca y los anchos
(clásico o BigTIFF), recorrer la cadena de directorios con sus topes, y armar la cabecera. Aquí
se arman TIFF a mano, byte a byte, para ejercitar **cada rama** —cadenas con pirámides,
máscaras y «menores sin declarar», ciclos, topes, directorios truncados, valores apuntados,
tipos raros— y se fija lo que devuelve hoy cada uno.

Complementa a `test_tiff.py`, que prueba la corrección del lector con el oráculo de su
constructor; esto solo congela el comportamiento para que el refactor no lo cambie.
"""

from __future__ import annotations

import dataclasses
import struct
from pathlib import Path

import pytest

from apps.formats import tiff

SHORT, LONG, ASCII, DOUBLE, RATIONAL, LONG8 = 3, 4, 2, 12, 5, 16
_STRUCT = {1: "B", 3: "H", 4: "I", 12: "d", 16: "Q"}


def _tiff(ifds, *, orden="<", big=False, siguientes=None, marca=None, cola=b"") -> bytes:
    """Un TIFF armado a mano. `ifds` es una lista de `{etiqueta: (tipo, valores[, cuenta])}`.

    Los valores que no caben en el hueco van a un área detrás de los directorios, y cada IFD
    apunta al siguiente (o a lo que diga `siguientes[i]`, para fabricar ciclos).
    """
    hueco = 8 if big else 4
    ancho_off = "Q" if big else "I"
    tam_ifd = (lambda n: 8 + n * 20 + 8) if big else (lambda n: 2 + n * 12 + 4)
    inicio = 16 if big else 8

    posiciones, pos = [], inicio
    for ifd in ifds:
        posiciones.append(pos)
        pos += tam_ifd(len(ifd))
    base_area, area = pos, bytearray()

    cuerpos = []
    for i, ifd in enumerate(ifds):
        entradas = b""
        for etiqueta in sorted(ifd):
            entrada = ifd[etiqueta]
            tipo, valores = entrada[0], entrada[1]
            if isinstance(valores, bytes):
                datos, cuenta = valores, len(valores)
            else:
                datos = b"".join(struct.pack(orden + _STRUCT[tipo], v) for v in valores)
                cuenta = len(valores)
            if len(entrada) == 3:
                cuenta = entrada[2]
            if len(datos) <= hueco:
                valor = datos.ljust(hueco, b"\x00")
            else:
                valor = struct.pack(orden + ancho_off, base_area + len(area))
                area += datos
            entradas += (
                struct.pack(orden + "HH", etiqueta, tipo)
                + struct.pack(orden + ancho_off, cuenta)
                + valor
            )
        if siguientes and i in siguientes:
            sig = siguientes[i]
        else:
            sig = posiciones[i + 1] if i + 1 < len(ifds) else 0
        n = struct.pack(orden + ("Q" if big else "H"), len(ifd))
        cuerpos.append(n + entradas + struct.pack(orden + ancho_off, sig))

    marca_orden = b"II" if orden == "<" else b"MM"
    if big:
        cabecera = marca_orden + struct.pack(orden + "HHH", 43, 8, 0)
        cabecera += struct.pack(orden + "Q", posiciones[0] if ifds else 0)
    else:
        cabecera = marca_orden + struct.pack(orden + "H", 42)
        cabecera += struct.pack(orden + "I", posiciones[0] if ifds else 0)
    if marca is not None:
        cabecera = marca + cabecera[len(marca) :]
    return cabecera + b"".join(cuerpos) + bytes(area) + cola


def _principal(extra=None):
    """El IFD principal mínimo: 100×80, una banda de 8 bits."""
    ifd = {
        256: (SHORT, [100]),
        257: (SHORT, [80]),
        258: (SHORT, [8]),
        259: (SHORT, [1]),
        262: (SHORT, [1]),
        277: (SHORT, [1]),
    }
    ifd.update(extra or {})
    return ifd


def _reducido(ancho, bandera=None):
    ifd = {256: (SHORT, [ancho]), 257: (SHORT, [ancho * 4 // 5])}
    if bandera is not None:
        ifd[254] = (LONG, [bandera])
    return ifd


GEOCLAVES = (1, 1, 0, 2, 1024, 0, 1, 1, 3072, 0, 1, 32719)

CASOS: dict[str, bytes] = {
    "clasico-le": _tiff([_principal()]),
    "clasico-be": _tiff([_principal()], orden=">"),
    "bigtiff-le": _tiff([_principal()], big=True),
    "bigtiff-be": _tiff([_principal()], big=True, orden=">"),
    "con-geo": _tiff(
        [
            _principal(
                {
                    33550: (DOUBLE, [0.5, 0.5, 0.0]),
                    33922: (DOUBLE, [0, 0, 0, 500000.0, 7000000.0, 0]),
                    34735: (SHORT, GEOCLAVES),
                    305: (ASCII, b"Metashape 2.1\x00"),
                }
            )
        ]
    ),
    "tres-piramides-declaradas": _tiff(
        [_principal(), _reducido(50, 1), _reducido(25, 1), _reducido(12, 1)]
    ),
    "con-mascara": _tiff([_principal(), _reducido(100, 4), _reducido(50, 5)]),
    "menores-sin-declarar": _tiff([_principal(), _reducido(50), _reducido(25)]),
    "igual-de-ancho-no-cuenta": _tiff([_principal(), _reducido(100)]),
    "mas-ancho-no-cuenta": _tiff([_principal(), _reducido(200)]),
    "ifd-extra-sin-ancho-ni-bandera": _tiff([_principal(), {258: (SHORT, [8])}]),
    "ifd-extra-con-otras-etiquetas": _tiff(
        [_principal(), {**_reducido(50, 1), 259: (SHORT, [8]), 305: (ASCII, b"otro\x00")}]
    ),
    "ciclo-sobre-si-mismo": _tiff([_principal()], siguientes={0: 8}),
    "ciclo-entre-dos": _tiff([_principal(), _reducido(50, 1)], siguientes={1: 8}),
    "setenta-directorios": _tiff([_principal()] + [_reducido(50, 1)] * 69),
    "ifd-siguiente-fuera-del-archivo": _tiff([_principal()], siguientes={0: 99_999}),
    "ifd-truncado": _tiff([_principal(), _reducido(50, 1)])[:-12],
    "ifd-principal-truncado": _tiff([_principal()])[:40],
    "ifd0-sin-entradas": _tiff([{}]),
    "ifd-con-demasiadas-entradas": (
        b"II*\x00\x08\x00\x00\x00" + struct.pack("<H", 5000) + bytes(60)
    ),
    "cadena-de-un-solo-ifd-pero-segundo-vacio": _tiff([_principal(), {}]),
    "sin-ancho": _tiff([{257: (SHORT, [80])}]),
    "sin-alto": _tiff([{256: (SHORT, [100])}]),
    "tipo-racional-se-ignora": _tiff(
        [_principal({282: (RATIONAL, b"\x01\x00\x00\x00\x01\x00\x00\x00")})]
    ),
    "tipo-desconocido": _tiff([_principal({40000: (99, b"abcd")})]),
    "cuenta-absurda": _tiff([_principal({33550: (DOUBLE, b"\x00" * 8, 10_000_000)})]),
    "valor-apuntado-fuera-del-archivo": _tiff(
        [_principal({33550: (DOUBLE, b"\x00" * 16, 2)})], cola=b""
    )[:-8],
    "teselado": _tiff([_principal({322: (SHORT, [256]), 323: (SHORT, [256])})]),
    "franjas": _tiff([_principal({278: (SHORT, [16])})]),
    "alfa": _tiff([_principal({277: (SHORT, [4]), 338: (SHORT, [2])})]),
    "escala-incompleta": _tiff([_principal({33550: (DOUBLE, [0.5])})]),
    "atadura-incompleta": _tiff([_principal({33922: (DOUBLE, [0, 0, 0])})]),
    "geoclaves-geograficas": _tiff(
        [_principal({34735: (SHORT, (1, 1, 0, 2, 1024, 0, 1, 2, 2048, 0, 1, 4326))})]
    ),
    "geoclaves-definidas-por-el-usuario": _tiff(
        [_principal({34735: (SHORT, (1, 1, 0, 1, 3072, 0, 1, 32767))})]
    ),
    "geoclaves-cortas": _tiff([_principal({34735: (SHORT, (1, 1, 0))})]),
    "bigtiff-con-piramide-y-mascara": _tiff(
        [_principal(), _reducido(50, 1), _reducido(100, 4)], big=True
    ),
    "bigtiff-con-valores-apuntados": _tiff(
        [_principal({33550: (DOUBLE, [0.5, 0.5, 0.0]), 305: (ASCII, b"Hola mundo\x00")})],
        big=True,
    ),
    # --- los que levantan NoEsTiff -------------------------------------------------
    "menos-de-ocho-bytes": b"II*\x00\x00",
    "marca-de-orden-mala": b"XX*\x00\x08\x00\x00\x00" + bytes(20),
    "version-mala": _tiff([_principal()])[:2] + struct.pack("<H", 99) + bytes(20),
    "bigtiff-con-desplazamientos-de-4": (
        b"II+\x00" + struct.pack("<HH", 4, 0) + struct.pack("<Q", 16) + bytes(40)
    ),
}


def _calcular(tmp_path: Path, caso: str) -> dict:
    ruta = tmp_path / "x.tif"
    ruta.write_bytes(CASOS[caso])
    try:
        cabecera = tiff.leer_cabecera(ruta)
    except tiff.NoEsTiff as fallo:
        return {"levanta": "NoEsTiff", "mensaje": str(fallo)}
    foto = dataclasses.asdict(cabecera)
    foto["_propiedades"] = {
        "nombre_compresion": cabecera.nombre_compresion,
        "nombre_fotometria": cabecera.nombre_fotometria,
        "tiene_alfa": cabecera.tiene_alfa,
        "megapixeles": cabecera.megapixeles,
        "tiene_piramides_internas": cabecera.tiene_piramides_internas,
        "bytes_sin_comprimir": cabecera.bytes_sin_comprimir,
        "gsd_cm": cabecera.gsd_cm,
        "extension_terreno_m": cabecera.extension_terreno_m,
        "necesitaba_bigtiff": cabecera.necesitaba_bigtiff,
    }
    return foto


#: Lo que devuelve **hoy** cada caso (generado con el código sin tocar y revisado a ojo).
ESPERADO: dict[str, dict] = {
    "alfa": {
        "_propiedades": {
            "bytes_sin_comprimir": 32000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": True,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 4,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (2,),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "atadura-incompleta": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "bigtiff-be": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": True,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": False,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "bigtiff-con-desplazamientos-de-4": {
        "levanta": "NoEsTiff",
        "mensaje": "BigTIFF con desplazamientos de 4 bytes: no soportado.",
    },
    "bigtiff-con-piramide-y-mascara": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": True,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 3,
        "epsg": None,
        "es_bigtiff": True,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 1,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 1,
        "software": "",
        "teselado": False,
    },
    "bigtiff-con-valores-apuntados": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": (50.0, 40.0),
            "gsd_cm": 50.0,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": True,
        "escala_pixel": (0.5, 0.5),
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "Hola mundo",
        "teselado": False,
    },
    "bigtiff-le": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": True,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "cadena-de-un-solo-ifd-pero-segundo-vacio": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "ciclo-entre-dos": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": True,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 2,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 1,
        "software": "",
        "teselado": False,
    },
    "ciclo-sobre-si-mismo": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "clasico-be": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": False,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "clasico-le": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "con-geo": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": (50.0, 40.0),
            "gsd_cm": 50.0,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": 32719,
        "es_bigtiff": False,
        "escala_pixel": (0.5, 0.5),
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": (500000.0, 7000000.0),
        "reducciones": 0,
        "software": "Metashape 2.1",
        "teselado": False,
    },
    "con-mascara": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 3,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 2,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "cuenta-absurda": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "escala-incompleta": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "franjas": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": 16,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "geoclaves-cortas": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "geoclaves-definidas-por-el-usuario": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "geoclaves-geograficas": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": 4326,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "ifd-con-demasiadas-entradas": {
        "levanta": "NoEsTiff",
        "mensaje": "El primer directorio no declara ancho y alto.",
    },
    "ifd-extra-con-otras-etiquetas": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": True,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 2,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 1,
        "software": "",
        "teselado": False,
    },
    "ifd-extra-sin-ancho-ni-bandera": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 2,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "ifd-principal-truncado": {
        "levanta": "NoEsTiff",
        "mensaje": "El primer directorio no declara ancho y alto.",
    },
    "ifd-siguiente-fuera-del-archivo": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "ifd-truncado": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 2,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "ifd0-sin-entradas": {
        "levanta": "NoEsTiff",
        "mensaje": "El primer directorio no declara ancho y alto.",
    },
    "igual-de-ancho-no-cuenta": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 2,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "marca-de-orden-mala": {
        "levanta": "NoEsTiff",
        "mensaje": "No empieza con II ni MM, sino con b'XX'.",
    },
    "mas-ancho-no-cuenta": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 2,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "menores-sin-declarar": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 3,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 2,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "menos-de-ocho-bytes": {"levanta": "NoEsTiff", "mensaje": "El archivo tiene menos de 8 bytes."},
    "setenta-directorios": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": True,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 64,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 63,
        "software": "",
        "teselado": False,
    },
    "sin-alto": {"levanta": "NoEsTiff", "mensaje": "El primer directorio no declara ancho y alto."},
    "sin-ancho": {
        "levanta": "NoEsTiff",
        "mensaje": "El primer directorio no declara ancho y alto.",
    },
    "teselado": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": 256,
        "ancho_px": 100,
        "ancho_tesela": 256,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": True,
    },
    "tipo-desconocido": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "tipo-racional-se-ignora": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "tres-piramides-declaradas": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": True,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 4,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 3,
        "software": "",
        "teselado": False,
    },
    "valor-apuntado-fuera-del-archivo": {
        "_propiedades": {
            "bytes_sin_comprimir": 8000,
            "extension_terreno_m": None,
            "gsd_cm": None,
            "megapixeles": 0.008,
            "necesitaba_bigtiff": False,
            "nombre_compresion": "sin comprimir",
            "nombre_fotometria": "negro es cero",
            "tiene_alfa": False,
            "tiene_piramides_internas": False,
        },
        "alto_px": 80,
        "alto_tesela": None,
        "ancho_px": 100,
        "ancho_tesela": None,
        "bandas": 1,
        "bits_por_muestra": 8,
        "compresion": 1,
        "directorios": 1,
        "epsg": None,
        "es_bigtiff": False,
        "escala_pixel": None,
        "filas_por_franja": None,
        "fotometria": 1,
        "little_endian": True,
        "mascaras": 0,
        "menores_sin_declarar": 0,
        "muestras_extra": (),
        "origen": None,
        "reducciones": 0,
        "software": "",
        "teselado": False,
    },
    "version-mala": {
        "levanta": "NoEsTiff",
        "mensaje": "Marca de version 99: no es 42 (clasico) ni 43 (BigTIFF).",
    },
}


@pytest.mark.parametrize("caso", sorted(CASOS))
def test_lo_que_devuelve_hoy(tmp_path, caso):
    assert _calcular(tmp_path, caso) == ESPERADO[caso]
