# Generated by Django 6.1 on 2026-09-08 16:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_path', models.CharField(blank=True, max_length=1000)),
                ('source_upload', models.FileField(blank=True, upload_to='entradas/%Y/%m/')),
                ('source_name', models.CharField(max_length=255)),
                ('source_size_bytes', models.BigIntegerField(default=0)),
                ('source_sha256', models.CharField(blank=True, max_length=64)),
                ('source_format_code', models.CharField(blank=True, max_length=40)),
                ('source_format_confidence', models.CharField(blank=True, max_length=16)),
                ('source_crs_authority', models.CharField(blank=True, max_length=16)),
                ('source_crs_code', models.CharField(blank=True, max_length=16)),
                ('source_crs_wkt', models.TextField(blank=True)),
                ('source_crs_origin', models.CharField(blank=True, max_length=16)),
                ('target_crs_authority', models.CharField(blank=True, max_length=16)),
                ('target_crs_code', models.CharField(blank=True, max_length=16)),
                ('target_format_code', models.CharField(max_length=40)),
                ('target_profile_id', models.CharField(blank=True, max_length=40)),
                ('engine_id', models.CharField(blank=True, max_length=60)),
                ('engine_version', models.CharField(blank=True, max_length=200)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('verifying', 'Verifying'), ('done', 'Done'), ('error', 'Error'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='queued', max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=40)),
                ('reason_detail', models.TextField(blank=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('progress_stage', models.CharField(blank=True, choices=[('huella', 'Fingerprint'), ('inspeccion', 'Inspection'), ('conversion', 'Conversion'), ('verificacion', 'Verification')], max_length=24)),
                ('progress_updated_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('worker_pid', models.PositiveIntegerField(blank=True, null=True)),
                ('worker_host', models.CharField(blank=True, max_length=80)),
                ('output_path', models.CharField(blank=True, max_length=1000)),
                ('output_size_bytes', models.BigIntegerField(default=0)),
                ('output_sha256', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to=settings.AUTH_USER_MODEL)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reintentos', to='jobs.conversionjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('cancelar_conversionjob', 'Puede cancelar un trabajo de conversion'), ('reencolar_conversionjob', 'Puede reencolar un trabajo')],
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveBigIntegerField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('error', 'Error')], default='info', max_length=8)),
                ('stage', models.CharField(blank=True, max_length=24)),
                ('message', models.TextField()),
                ('reason_code', models.CharField(blank=True, max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='jobs.conversionjob')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['status', 'queued_at'], name='job_cola_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobevent',
            unique_together={('job', 'sequence')},
        ),
    ]
