# Generated by Django 6.1 on 2026-09-25 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='desenlace',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='herramienta',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='EntradaDeTrabajo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveSmallIntegerField()),
                ('papel', models.CharField(blank=True, choices=[('', 'Input'), ('hoja', 'Sheet'), ('plantilla', 'Template')], max_length=16)),
                ('ruta', models.CharField(max_length=1000)),
                ('nombre', models.CharField(max_length=255)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('bytes', models.BigIntegerField(default=0)),
                ('mtime_ns', models.BigIntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='jobs.conversionjob')),
                ('subida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_de_trabajo', to='core.archivosubido')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('job', 'orden')},
            },
        ),
    ]
