# Generated by Django 6.1.1 on 2026-10-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_documentos_en_cola'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='progress_label',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='entradadetrabajo',
            name='papel',
            field=models.CharField(blank=True, choices=[('', 'Input'), ('hoja', 'Sheet'), ('plantilla', 'Template'), ('trayectoria', 'Trajectory'), ('disparos', 'Camera events'), ('referencia', 'Reference positions')], max_length=16),
        ),
    ]
