# Generated by Django 6.1.1 on 2026-10-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_lotes_y_paquetes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversionjob',
            options={'ordering': ['-created_at'], 'permissions': [('cancelar_conversionjob', 'Puede cancelar un trabajo de conversion'), ('reencolar_conversionjob', 'Puede reencolar un trabajo'), ('usar_api', 'Puede convertir por la API')]},
        ),
    ]
