# Generated by Django 6.1.1 on 2026-10-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_api_con_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadetrabajo',
            name='papel',
            field=models.CharField(blank=True, choices=[('', 'Input'), ('hoja', 'Sheet'), ('plantilla', 'Template'), ('trayectoria', 'Trajectory'), ('disparos', 'Camera events'), ('referencia', 'Reference positions'), ('rover', 'Drone observations'), ('base', 'Base station observations'), ('navegacion', 'Navigation ephemerides')], max_length=16),
        ),
    ]
