# Generated by Django 6.1 on 2026-09-14 13:12

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoSubido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to=apps.core.models.donde_guardar)),
                ('nombre_original', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'archivo subido',
                'verbose_name_plural': 'archivos subidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruta', models.CharField(max_length=1000)),
                ('nombre', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('herramienta', models.CharField(blank=True, max_length=40)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resultado',
                'verbose_name_plural': 'resultados',
                'ordering': ['-created_at'],
            },
        ),
    ]
