# Generated by Django 6.1.1 on 2026-10-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
