# Generated by Django 6.1.1 on 2026-10-06 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_retirar_resultado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('servidor-500', 'Error del servidor'), ('navegador', 'Fallo visto desde el navegador')], db_index=True, max_length=24)),
                ('ruta', models.CharField(max_length=200)),
                ('estado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=300)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'incidente',
                'verbose_name_plural': 'incidentes',
                'ordering': ['-created_at'],
            },
        ),
    ]
