# Generated by Django 6.1 on 2026-09-09 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('target_format_code', models.CharField(max_length=40)),
                ('target_profile_id', models.CharField(blank=True, max_length=40)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('target_crs_code', models.CharField(blank=True, max_length=16)),
                ('de_fabrica', models.BooleanField(default=False)),
                ('veces_usado', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preajustes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-de_fabrica', '-veces_usado', 'nombre'],
                'permissions': [('compartir_conversionpreset', 'Puede compartir un preajuste')],
            },
        ),
    ]
