# Generated by Django 6.1.1 on 2026-10-08 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteDeEntrega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('pasos', models.JSONField(default=list)),
                ('patron_de_nombre', models.CharField(default='{origen}_{destino}', max_length=120)),
                ('target_crs_code', models.CharField(blank=True, max_length=16)),
                ('veces_usado', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_de_entrega', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-veces_usado', 'nombre'],
            },
        ),
    ]
