# Generated by Django 6.1.1 on 2026-10-08 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDeSonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(db_index=True, max_length=60)),
                ('disponible', models.BooleanField()),
                ('codigo_motivo', models.CharField(blank=True, max_length=60)),
                ('mensaje', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=120)),
                ('visto_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-visto_en', '-id'),
                'indexes': [models.Index(fields=['motor', '-visto_en'], name='engines_reg_motor_8aaaf7_idx')],
            },
        ),
    ]
